import Link from "next/link";
import { AlertTriangle } from "lucide-react";

export const metadata = {
  title: "Privacy Policy — Cash Flow Forecaster",
};

export default function PrivacyPage() {
  return (
    <div className="legal-shell">
      <nav className="legal-nav">
        <div className="brand">
          <div className="brand-mark">CF</div>
          <span className="landing-nav-name">Cash Flow Forecaster</span>
        </div>
        <Link className="btn-secondary" href="/">
          Back to home
        </Link>
      </nav>

      <div className="legal-content">
        <h1 className="display">Privacy Policy</h1>
        <p className="legal-updated">
          Last updated: <span className="legal-placeholder">[EFFECTIVE DATE]</span>
        </p>

        <div className="tip insight legal-draft-notice">
          <span className="tip-icon">
            <AlertTriangle size={15} />
          </span>
          <p>
            <strong>Draft — not yet reviewed by counsel.</strong>{" "}
            This page is placeholder content generated to scaffold a real privacy policy. Every bracketed field needs to be filled in, the substance needs to be checked against how the product actually works, and it needs sign-off from a lawyer before it&apos;s relied on. Don&apos;t treat this as a live legal document until that&apos;s done.
          </p>
        </div>

        <p>
          <span className="legal-placeholder">[COMPANY LEGAL NAME]</span>{" "}
          (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates Cash Flow Forecaster (the &quot;Service&quot;). This Privacy Policy explains what information we collect, how we use it, who we share it with, and the choices you have. By creating an account or otherwise using the Service, you agree to the collection and use of information in accordance with this policy.
        </p>

        <h2>1. Information we collect</h2>
        <p>We collect the following categories of information:</p>
        <ul>
          <li>
            <strong>Account information:</strong>{" "}
            email address, company name, and a hashed password when you create an account. We never store your password in plain text.
          </li>
          <li>
            <strong>Financial forecast data:</strong>{" "}
            the income, expense, and balance figures you or your team enter — including line items, category labels, recurring payment schedules, manual overrides, and any &quot;actual&quot; figures you record against the forecast.
          </li>
          <li>
            <strong>Team and activity data:</strong>{" "}
            if you invite teammates, we store their email address, assigned role, and a log of account activity (who changed what and when) for accountability within your company&apos;s workspace.
          </li>
          <li>
            <strong>Usage data:</strong>{" "}
            basic technical information generated by using the Service, such as IP address, browser type, and error/crash reports, collected through the third-party tools described below.
          </li>
        </ul>

        <h2>2. How we use your information</h2>
        <ul>
          <li>To provide, maintain, and operate the Service, including generating your forecast.</li>
          <li>To authenticate your account and keep your data isolated from other companies&apos; data.</li>
          <li>To send transactional emails you&apos;ve triggered — password resets, team invitations, and cash flow alerts.</li>
          <li>To detect, investigate, and fix bugs or security issues.</li>
          <li>To comply with legal obligations.</li>
        </ul>
        <p>We do not sell your personal information, and we do not use your financial data for advertising.</p>

        <h2>3. Who we share information with</h2>
        <p>
          We use the following third-party service providers to operate the Service. Each processes data on our behalf and only to the extent necessary to provide their service:
        </p>
        <ul>
          <li><strong>Neon</strong> — hosts our production database (all account and forecast data).</li>
          <li><strong>Resend</strong> — delivers transactional emails (invites, password resets, alerts).</li>
          <li><strong>Sentry</strong> — error monitoring, used to detect and diagnose bugs.</li>
          <li><strong>Vercel</strong> — hosts and serves the application.</li>
        </ul>
        <p>
          We do not share your data with any other third party except where required by law, to protect our rights, or with your explicit consent.{" "}
          <span className="legal-placeholder">[CONFIRM SUBPROCESSOR LIST IS CURRENT]</span>
        </p>

        <h2>4. Cookies</h2>
        <p>
          We use a single strictly-necessary session cookie to keep you signed in. It expires automatically after a period of inactivity. We do not use advertising or cross-site tracking cookies, and we do not currently use analytics cookies.
        </p>

        <h2>5. Data retention</h2>
        <p>
          We retain your account and forecast data for as long as your account is active.{" "}
          <span className="legal-placeholder">[DESCRIBE ACTUAL DELETION PROCESS AND TIMELINE ONCE BUILT]</span>
        </p>

        <h2>6. Your rights</h2>
        <p>
          Depending on where you live, you may have the right to access, correct, export, or delete your personal information, and to object to or restrict certain processing. To exercise any of these rights, contact us at{" "}
          <span className="legal-placeholder">[PRIVACY CONTACT EMAIL]</span>.
        </p>

        <h2>7. Data security</h2>
        <p>
          We use industry-standard measures to protect your data, including encrypted password storage, encrypted connections (HTTPS/TLS), and role-based access controls within each company&apos;s workspace. No method of transmission or storage is 100% secure, and we cannot guarantee absolute security.
        </p>

        <h2>8. Children&apos;s privacy</h2>
        <p>
          The Service is intended for business use and is not directed to individuals under 18. We do not knowingly collect personal information from children.
        </p>

        <h2>9. International data transfers</h2>
        <p>
          Your information may be processed in{" "}
          <span className="legal-placeholder">[HOSTING REGION(S)]</span>, which may differ from the laws of your country of residence.
        </p>

        <h2>10. Changes to this policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will notify you of material changes by{" "}
          <span className="legal-placeholder">[NOTIFICATION METHOD, e.g. email or an in-app notice]</span>.
        </p>

        <h2>11. Contact us</h2>
        <p>
          Questions about this policy? Contact us at{" "}
          <span className="legal-placeholder">[CONTACT EMAIL]</span>{" "}
          or{" "}
          <span className="legal-placeholder">[MAILING ADDRESS]</span>.
        </p>
      </div>
    </div>
  );
}
